export const pikaraokeScoreReviews = {
  low: [
    "{name}, nunca mais cante... nunca!",
    "{name}, isso foi uma ótima imitação de um gato morrendo!",
    "Graças a Deus acabou, {name}.",
    "{name}, passa o microfone, por favor!",
    "Bom {name}, tenho certeza que você é muito bom no seu trabalho...",
    "{name}, meus ouvidos estão sangrando!",
    "{name}, isso foi... uma escolha.",
    "Eita {name}, o que foi isso?!",
    "{name}, você tentou pelo menos...",
  ],
  mid: [
    "{name}, já vi melhores.",
    "Ok {name}... só ok.",
    "Nada mal pra um amador, {name}!",
    "{name}, você fez um show decente.",
    "{name}, isso foi... algo.",
    "Quase lá, {name}!",
    "{name}, precisa treinar mais um pouquinho.",
    "Tá melhorando, {name}!",
    "{name}, dá pro gasto!",
  ],
  high: [
    "Parabéns {name}! Isso foi incrível!",
    "Uau {name}, você já tentou ir no The Voice?",
    "{name}, por favor, cante mais uma!",
    "{name}, você arrasa! Sabia disso?!",
    "Eita, quem deixou o {name} entrar? Que talento!",
    "{name}, isso sim é talento!",
    "{name}, você nasceu pra isso!",
    "A plateia foi à loucura com {name}!",
    "{name} mitou! 🔥",
    "Simplesmente {name}! Arrasou!",
  ],
} as const;
